### ISSUE TITLE
Samram Project feedbacks and tasks

### ISSUE THREAD

**Issue by tykealy** [channainfo/commissioner#1437]
**Product**
- [x] #1480 
- [x] Change from Taxon to Business
- [x] #1454
- [x] #1446

**Place**
- [x] #1445
- [x] Don't display customer_count 

**Taxon**
- [x] #1439
- [x] Rearrange taxon structure. Ex: Business/សណ្ធាគារ និងផ្ទះសំណាក់/ផ្ទះសំណាក់ (គិតចំនួនបន្ទប់)

**Customer**
- [x] customer_index_page: show owner_name and business_name separately
- [x] customer_new_page: Change location->place, taxon->business
- [x] Store customer business taxon in separate column
- [x] Store customer product taxon in separate column
- [x] #1443
- [x] #1475

**Subscribe**
- [x] #1448
- [x] #1469
- [x] #1472

**Invoice**
- [x] Invoice recurring automation
- [x] #1462 
- [x] Refine invoice UI
- [x] #1455
- [x] #1484
- [x] Link back to customer
- [x] Check invoice UI(color....)

**Report**
- [x] bigger number
- [x] Center column
- [x] provide clear parameter while filtering

*Firady 31th May 2024*

**Customer's invoices list**
- [x] sort by descending order
- [x] for latest invoice, add an indicator
- [x] add a colum for month name

**Comment by channainfo** [comment]
@tykealy let's keep the seeds the last resort coz they don't affect the product demo.

**Comment by AhKaRY** [comment]
![Screenshot 2024-06-04 112523](https://github.com/channainfo/commissioner/assets/134909582/4ffc8767-fea4-4a83-9259-03a316f81e91)

@tykealy @Regene27 

Seem like when filtering the report page under Report -> Report

You capture it via all subscripted variants rather than just order, as a result to that if the customer has subscripted to 3 variant/business type then the invoice will appear 3 times. 

Please kindly check it out. 

Thank you

**Comment by AhKaRY** [comment]
https://github.com/channainfo/commissioner/assets/134909582/f255f5a9-e493-47b0-9778-16be31a872ea

@tykealy @channainfo @Regene27 

The Report section does not show all inputted products, For example: there should be at least 18 products inputted it only shows at most 12 products. 

Please check it.
